version: "3.7"

services:
  amazin-object-storage-node-1: &object-storage-node
    image: minio/minio
    command: server --console-address ":9001" /tmp/data
    ports: [ "9001:9001" ]
    networks:
      amazin-object-storage:
        ipv4_address: 169.253.0.2
    environment:
      - MINIO_ACCESS_KEY=ring
      - MINIO_SECRET_KEY=treepotato

  amazin-object-storage-node-2:
    <<: *object-storage-node
    ports: [ "9002:9001" ]
    networks:
      amazin-object-storage:
        ipv4_address: 169.253.0.3
    environment:
      - MINIO_ACCESS_KEY=maglev
      - MINIO_SECRET_KEY=baconpapaya

  amazin-object-storage-node-3:
    <<: *object-storage-node
    ports: [ "9003:9001" ]
    networks:
      amazin-object-storage:
        ipv4_address: 169.253.0.4
    environment:
      - MINIO_ACCESS_KEY=rendezvous
      - MINIO_SECRET_KEY=bluegreen

  gateway-container: 
    build: .
    ports: [ "3000:3000" ]
    networks:
      amazin-object-storage:
        ipv4_address: 169.253.0.5
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

networks:
  amazin-object-storage:
    ipam:
      driver: default
      config:
        - subnet: 169.253.0.0/24
          gateway: 169.253.0.1
