// Code generated by MockGen. DO NOT EDIT.
// Source: object-storage-gateway/internal/gateway (interfaces: MinioClient,MinioObject,MinioClientWrapper)

// Package gateway is a generated GoMock package.
package gateway

import (
	context "context"
	reflect "reflect"

	minio "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockMinioClient is a mock of MinioClient interface.
type MockMinioClient struct {
	ctrl     *gomock.Controller
	recorder *MockMinioClientMockRecorder
}

// MockMinioClientMockRecorder is the mock recorder for MockMinioClient.
type MockMinioClientMockRecorder struct {
	mock *MockMinioClient
}

// NewMockMinioClient creates a new mock instance.
func NewMockMinioClient(ctrl *gomock.Controller) *MockMinioClient {
	mock := &MockMinioClient{ctrl: ctrl}
	mock.recorder = &MockMinioClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinioClient) EXPECT() *MockMinioClientMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockMinioClient) GetObject(arg0 context.Context, arg1, arg2 string, arg3 minio.GetObjectOptions) (*minio.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*minio.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockMinioClientMockRecorder) GetObject(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockMinioClient)(nil).GetObject), arg0, arg1, arg2, arg3)
}

// MockMinioObject is a mock of MinioObject interface.
type MockMinioObject struct {
	ctrl     *gomock.Controller
	recorder *MockMinioObjectMockRecorder
}

// MockMinioObjectMockRecorder is the mock recorder for MockMinioObject.
type MockMinioObjectMockRecorder struct {
	mock *MockMinioObject
}

// NewMockMinioObject creates a new mock instance.
func NewMockMinioObject(ctrl *gomock.Controller) *MockMinioObject {
	mock := &MockMinioObject{ctrl: ctrl}
	mock.recorder = &MockMinioObjectMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinioObject) EXPECT() *MockMinioObjectMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockMinioObject) Read(arg0 []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockMinioObjectMockRecorder) Read(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockMinioObject)(nil).Read), arg0)
}

// MockMinioClientWrapper is a mock of MinioClientWrapper interface.
type MockMinioClientWrapper struct {
	ctrl     *gomock.Controller
	recorder *MockMinioClientWrapperMockRecorder
}

// MockMinioClientWrapperMockRecorder is the mock recorder for MockMinioClientWrapper.
type MockMinioClientWrapperMockRecorder struct {
	mock *MockMinioClientWrapper
}

// NewMockMinioClientWrapper creates a new mock instance.
func NewMockMinioClientWrapper(ctrl *gomock.Controller) *MockMinioClientWrapper {
	mock := &MockMinioClientWrapper{ctrl: ctrl}
	mock.recorder = &MockMinioClientWrapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinioClientWrapper) EXPECT() *MockMinioClientWrapperMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockMinioClientWrapper) GetObject(arg0 context.Context, arg1, arg2 string, arg3 minio.GetObjectOptions) (MinioObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(MinioObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockMinioClientWrapperMockRecorder) GetObject(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockMinioClientWrapper)(nil).GetObject), arg0, arg1, arg2, arg3)
}
